// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuitionManagement.Data;

#nullable disable

namespace TuitionManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605123412_NewTables")]
    partial class NewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuitionManagement.Data.Models.Batch", b =>
                {
                    b.Property<int>("BatchUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchUID"));

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MaxStrength")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BatchUID");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.BatchSchedule", b =>
                {
                    b.Property<int>("BatchScheduleUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BatchScheduleUID"));

                    b.Property<int>("BatchUID")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SubjectUID")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherUID")
                        .HasColumnType("integer");

                    b.HasKey("BatchScheduleUID");

                    b.HasIndex("BatchUID");

                    b.HasIndex("SubjectUID");

                    b.HasIndex("TeacherUID");

                    b.ToTable("BatchSchedules");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Student", b =>
                {
                    b.Property<int>("StudentUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentUID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StudentUID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.StudentBatch", b =>
                {
                    b.Property<int>("StudentBatchUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentBatchUID"));

                    b.Property<int>("BatchUID")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StudentUID")
                        .HasColumnType("integer");

                    b.HasKey("StudentBatchUID");

                    b.HasIndex("BatchUID");

                    b.HasIndex("StudentUID");

                    b.ToTable("StudentBatches");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Subject", b =>
                {
                    b.Property<int>("SubjectUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectUID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("SubjectUID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherUID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TeacherUID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.BatchSchedule", b =>
                {
                    b.HasOne("TuitionManagement.Data.Models.Batch", "Batch")
                        .WithMany("BatchSchedules")
                        .HasForeignKey("BatchUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagement.Data.Models.Subject", "Subject")
                        .WithMany("BatchSchedules")
                        .HasForeignKey("SubjectUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagement.Data.Models.Teacher", "Teacher")
                        .WithMany("BatchSchedules")
                        .HasForeignKey("TeacherUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.StudentBatch", b =>
                {
                    b.HasOne("TuitionManagement.Data.Models.Batch", "Batch")
                        .WithMany("StudentBatches")
                        .HasForeignKey("BatchUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuitionManagement.Data.Models.Student", "Student")
                        .WithMany("StudentBatches")
                        .HasForeignKey("StudentUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Batch", b =>
                {
                    b.Navigation("BatchSchedules");

                    b.Navigation("StudentBatches");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Student", b =>
                {
                    b.Navigation("StudentBatches");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Subject", b =>
                {
                    b.Navigation("BatchSchedules");
                });

            modelBuilder.Entity("TuitionManagement.Data.Models.Teacher", b =>
                {
                    b.Navigation("BatchSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
